# Generated by Django 2.0.4 on 2018-04-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('schematic', models.ImageField(upload_to='')),
                ('code', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
