# Generated by Django 2.0.4 on 2018-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
    ]
